# Generated by Django 4.2.20 on 2025-03-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=245)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sort_order', models.IntegerField()),
            ],
        ),
    ]
